[package]
name = "registry"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "registry"
path = "src/lib.rs"

[dependencies]
adapter.workspace = true
kernel.workspace = true
shared.workspace = true
mockall.workspace = true